[[ft]]
name = "bash"
regex = ".*\\.sh$"
shebang = "#!/bin/bash"
cmds = [
    ["shfmt", "-w", "-i", "4", "{{.filename}}"],
    ["shellcheck", "-e", "SC1090,SC2154", "{{.filename}}"],
    ["bats", "{{.shortname_no_ext}}_test.bats"]
]

[[ft]]
name = "bats"
regex = ".*\\.bats$"
shebang = "#!/usr/bin/env bats"
cmds = [
    ["bats", "{{.shortname_no_ext}}_test.bats"]
]

[[ft]]
name = "caddyfile"
regex = ".*/Caddyfile$"
cmds = [
    ["caddy", "fmt", "--overwrite", "{{.filename}}"]
]

[[ft]]
name = "golang"
regex = ".*\\.go$"
cmds = [
    ["goimports", "-w", "{{.filename}}"],
    ["gofmt", "-w", "{{.filename}}"],
    ["go", "test", "-v"]
]

[[ft]]
name = "markdown"
regex = ".*\\.md$"
cmds = [
    ["mdtoc", "-f", "{{.filename}}"],
    ["mdox", "fmt", "{{.filename}}"]
]

[[ft]]
name = "python"
regex = ".*\\.py$"
shebang = "#!/usr/bin/python3"
cmds = [
    ["autoflake", "--remove-all-unused-imports", "-i", "{{.filename}}"],
    ["isort", "{{.filename}}"],
    ["pytest", "-v", "{{.shortname_no_ext}}_test.py"]
]

[[ft]]
name = "rust"
regex = ".*\\.rs$"
cmds = [
    ["rustfmt", "{{.filename}}"],
    ["cargo", "test", "--color", "always"]
]

[settings]
ignore_list = [
    ".git/",
    ".pytest",
    "__pycache__",
    "/target/debug/",
    "/target/release/",
    ".lock$",
    ".rs.racertmp"
]
