[[ft]]
name = "bash"
regex = ".*\\.sh$"
shebang = "#!/bin/bash"
cmds = [
    ["shfmt", "-w", "-i", "4", "{FILENAME}"],
    ["shellcheck", "-e", "SC1090,SC2154", "{FILENAME}"],
    ["bats", "{SHORTNAME_NO_EXT}_test.bats"]
]

[[ft]]
name = "bats"
regex = ".*\\.bats$"
shebang = "#!/usr/bin/env bats"
cmds = [
    ["bats", "{SHORTNAME_NO_EXT}_test.bats"]
]

[[ft]]
name = "caddyfile"
regex = ".*/Caddyfile$"
cmds = [
    ["caddy", "fmt", "--overwrite", "{FILENAME}"]
]

[[ft]]
name = "golang"
regex = ".*\\.go$"
cmds = [
    ["go", "test", "-v"]
]

[[ft]]
name = "markdown"
regex = ".*\\.md$"
cmds = [
    ["mdtoc", "-f", "{FILENAME}"],
    ["markdownfmt", "-w", "{FILENAME}"]
]

[[ft]]
name = "python"
regex = ".*\\.py$"
shebang = "#!/usr/bin/python3"
cmds = [
    ["autoflake", "--remove-all-unused-imports", "-i", "{FILENAME}"],
    ["isort", "{FILENAME}"],
    ["pytest", "-v", "{SHORTNAME_NO_EXT}_test.py"]
]

[[ft]]
name = "rust"
regex = ".*\\.rs$"
cmds = [
    ["rustfmt", "{FILENAME}"],
    ["cargo", "test", "--color", "always"]
]

[settings]
ignore_list = [
    ".git/",
    ".pytest",
    "__pycache__",
    "/target/debug/",
    "/target/release/",
    ".lock$",
    ".rs.racertmp"
]
